/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    header: Header;
    footer: Footer;
    categories: Category;
    tags: Tag;
    posts: Post;
    testimonials: Testimonial;
    'review-statistics': ReviewStatistic;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'review-statistics': ReviewStatisticsSelect<false> | ReviewStatisticsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  name: string;
  logo: number | Media;
  navItems?:
    | {
        label: string;
        link: string;
        isExternal?: boolean | null;
        id?: string | null;
      }[]
    | null;
  navItemsForCta?:
    | {
        label: string;
        link: string;
        variant: 'primary' | 'secondary';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footerTitle: string;
  copyright?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  address?:
    | {
        city: string;
        state: string;
        postalCode: string;
        country: string;
        address: string;
        id?: string | null;
      }[]
    | null;
  contact?:
    | {
        email: string;
        phone: string;
        id?: string | null;
      }[]
    | null;
  footerNavigation?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  author: number | User;
  slug: string;
  featuredImage: number | Media;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: number | Category;
  tags?: (number | Tag)[] | null;
  status: 'draft' | 'published';
  publishedDate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  position: string;
  content: string;
  rating: '5' | '4' | '3' | '2' | '1';
  platform: 'google' | 'trustpilot' | 'airbnb' | 'yelp';
  authorImage: number | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-statistics".
 */
export interface ReviewStatistic {
  id: number;
  platform: 'google' | 'trustpilot' | 'airbnb' | 'yelp';
  reviewCount: number;
  averageRating: number;
  platformLogo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  sections?:
    | {
        sectionType:
          | 'hero'
          | 'aboutCoaching'
          | 'ourServices'
          | 'ourPotential'
          | 'ourExpertise'
          | 'introVideo'
          | 'processSteps'
          | 'companyGrowth'
          | 'ourFaq'
          | 'ourTestimonials'
          | 'ourBlogs';
        hero?: {
          label: string;
          heading: string;
          highlightedText: string;
          backgroundImage: number | Media;
          cta?: {
            label?: string | null;
            link?: string | null;
          };
          feature: {
            icon: number | Media;
            label?: string | null;
          };
        };
        aboutCoaching?: {
          label?: string | null;
          heading: string;
          highlightedText: string;
          description: string;
          mainImage: number | Media;
          secondaryImage: number | Media;
          experienceYears: number;
          clientCount: number;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          teamMembers?:
            | {
                image: number | Media;
                name: string;
                id?: string | null;
              }[]
            | null;
          award: {
            title: string;
            subtitle: string;
          };
          cta: {
            text: string;
            link: string;
          };
        };
        ourServices?: {
          label?: string | null;
          heading: string;
          highlightedText: string;
          description: string;
          service?:
            | {
                icon: number | Media;
                title: string;
                shortDescription: string;
                id?: string | null;
              }[]
            | null;
        };
        ourExpertise?: {
          label: string;
          heading: string;
          highlightedText: string;
          description: string;
          image: number | Media;
          metrics?:
            | {
                percentage: number;
                label: string;
                id?: string | null;
              }[]
            | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
        };
        ourPotential?: {
          label: string;
          heading: string;
          highlightedText: string;
          description: string;
          image: number | Media;
          metrics?:
            | {
                percentage: number;
                label: string;
                id?: string | null;
              }[]
            | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
        };
        videoSection?: {
          backgroundImage: number | Media;
          heading: string;
          highlightedText: string;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          videoUrl: string;
        };
        processSteps?: {
          label: string;
          heading: string;
          highlightedText: string;
          steps?:
            | {
                icon: number | Media;
                number: string;
                title: string;
                description: string;
                id?: string | null;
              }[]
            | null;
          keyFeatures?:
            | {
                title: string;
                id?: string | null;
              }[]
            | null;
        };
        statistics?: {
          label: string;
          heading: string;
          highlightedText: string;
          description: string;
          image: number | Media;
          stats?:
            | {
                value: string;
                label: string;
                description: string;
                id?: string | null;
              }[]
            | null;
        };
        companyGrowth?: {
          label: string;
          heading: string;
          highlightedText: string;
          description: string;
          image: number | Media;
          statistics?:
            | {
                'count/percentage': string;
                title: string;
                description: string;
                id?: string | null;
              }[]
            | null;
        };
        ourFaq?: {
          label: string;
          heading: string;
          highlightedText: string;
          description: string;
          faq?:
            | {
                teamMembers?:
                  | {
                      image: number | Media;
                      id?: string | null;
                    }[]
                  | null;
                phoneNumber: string;
                questions?:
                  | {
                      question: string;
                      answer: string;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'header';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'review-statistics';
        value: number | ReviewStatistic;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        isExternal?: T;
        id?: T;
      };
  navItemsForCta?:
    | T
    | {
        label?: T;
        link?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerTitle?: T;
  copyright?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  address?:
    | T
    | {
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        address?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        id?: T;
      };
  footerNavigation?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  tags?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  position?: T;
  content?: T;
  rating?: T;
  platform?: T;
  authorImage?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-statistics_select".
 */
export interface ReviewStatisticsSelect<T extends boolean = true> {
  platform?: T;
  reviewCount?: T;
  averageRating?: T;
  platformLogo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        sectionType?: T;
        hero?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              backgroundImage?: T;
              cta?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              feature?:
                | T
                | {
                    icon?: T;
                    label?: T;
                  };
            };
        aboutCoaching?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              mainImage?: T;
              secondaryImage?: T;
              experienceYears?: T;
              clientCount?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              teamMembers?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              award?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                  };
              cta?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
            };
        ourServices?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              service?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    shortDescription?: T;
                    id?: T;
                  };
            };
        ourExpertise?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              image?: T;
              metrics?:
                | T
                | {
                    percentage?: T;
                    label?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        ourPotential?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              image?: T;
              metrics?:
                | T
                | {
                    percentage?: T;
                    label?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        videoSection?:
          | T
          | {
              backgroundImage?: T;
              heading?: T;
              highlightedText?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              videoUrl?: T;
            };
        processSteps?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              keyFeatures?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
            };
        statistics?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
            };
        companyGrowth?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              image?: T;
              statistics?:
                | T
                | {
                    'count/percentage'?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        ourFaq?:
          | T
          | {
              label?: T;
              heading?: T;
              highlightedText?: T;
              description?: T;
              faq?:
                | T
                | {
                    teamMembers?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                        };
                    phoneNumber?: T;
                    questions?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}